"""command_center.py -- generate dashboard/COMMAND_CENTER.md.

Presentation/orchestration ONLY: summarizes existing outputs (ops report, evidence
ledger, shadow csv, fills csv, backlog, readiness doc). No calculations of its own
beyond counting rows; no fabricated values; missing files degrade to honest text.
Idempotent: same inputs -> byte-identical output (date-only stamp).

Usage: python scripts/ops/command_center.py
"""
import csv
import os
import re
from datetime import date

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(REPO, "dashboard", "COMMAND_CENTER.md")
TODAY = date.today()
MONTH_END = date(2026, 8, 16)   # reset from 08-11 by S2 fix 614e1ba
SHADOW_MIN_DAYS = 15


def read(p):
    fp = os.path.join(REPO, p)
    return open(fp, encoding="utf-8", errors="replace").read() if os.path.exists(fp) else ""


def rows(p):
    fp = os.path.join(REPO, p)
    if not os.path.exists(fp) or os.path.getsize(fp) == 0:
        return []
    with open(fp, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def bar(n, total, width=15):
    n = min(n, total)
    return "#" * round(width * n / total) + "-" * (width - round(width * n / total)) + f" {n}/{total}"


def main():
    ops = read("docs/DAILY_OPS_REPORT.md")
    ops_v = (re.search(r"## VERDICT: \*\*([\w ]+)\*\*", ops) or [None, "no report"])[1]
    ledger = read("docs/EVIDENCE_LEDGER.md")
    ledger_today = f"| {TODAY.isoformat()} |" in ledger
    sh = rows("research/results/shadow_signals.csv")
    fills = rows("logs/fills.csv")
    live_fills = [r for r in fills if str(r.get("dry_run", "")).lower() != "true"]
    backlog = read("docs/RESEARCH_BACKLOG.md")
    totals = (re.search(r"SHADOW (\d+) \| WAITING (\d+) \| REJECTED (\d+) \| ARCHIVED (\d+) \| READY (\d+)",
                        backlog) or [None] + ["?"] * 5)
    readiness = read("docs/PROP_READINESS.md")
    incidents = sorted(os.listdir(os.path.join(REPO, "vault", "08-Incidents-and-Postmortems"))
                       ) if os.path.isdir(os.path.join(REPO, "vault", "08-Incidents-and-Postmortems")) else []
    last_incident = next((i.replace(".md", "") for i in reversed(incidents) if i[0].isdigit()), "none on file")

    # health color: ops verdict + ledger freshness
    health = "GREEN" if ops_v == "HEALTHY" and ledger_today else \
             ("RED" if "ACTION" in ops_v else "YELLOW")

    # shadow accumulation
    sh_days = len({r["date"] for r in sh}) if sh else 0
    streams = sorted({r["stream"] for r in sh}) if sh else []

    # fills summary
    def num(col):
        vals = [float(r[col]) for r in live_fills if r.get(col) not in ("", None)]
        return f"{sum(vals)/len(vals):.1f} bps" if vals else "n/a"
    fills_today = [r for r in live_fills if r.get("timestamp_utc", "").startswith(TODAY.isoformat())]
    latest_fill = live_fills[-1]["timestamp_utc"] if live_fills else None

    days_left = max((MONTH_END - TODAY).days, 0)

    # TODAY logic: at most 3 items, exactly one primary recommendation
    if "ACTION" in ops_v:
        today_block = ["**Investigate the ops ACTION REQUIRED items** (docs/DAILY_OPS_REPORT.md)."]
    elif not ledger_today:
        today_block = ["**Run the daily evidence trio** -- `python scripts/router/task_router.py run` "
                       "(or the three scripts directly); today's ledger line is missing."]
    else:
        today_block = ["**Do nothing. Evidence month running.**"]
    standing = []
    if "rotation owed" in readiness or "rotate" in readiness.lower():
        standing.append("Standing (this week): rotate exposed secrets (readiness blocker #5).")
    if days_left <= 3:
        standing.append("Month-end near: export MT5 history (Toolbox -> Report) for closed-trade R stats.")
    today_block += standing[:2]

    L = []
    L.append(f"# COMMAND CENTER -- {TODAY.isoformat()}")
    L.append("\n_Generated by scripts/ops/command_center.py from existing artifacts. "
             "Regenerate anytime; never hand-edit._")
    L.append(f"\n## 1. SYSTEM HEALTH: **{health}**")
    L.append(f"- ops verdict (this host): **{ops_v}**")
    L.append(f"- evidence ledger today: {'YES' if ledger_today else 'NO -- run the daily trio'}")
    L.append("- VPS / gateway / watchdog: not visible from this host -- `python status.py` "
             "on the VPS is authoritative (tasks LastResult, MT5 connection, watchdog)")
    L.append(f"- last incident on file: {last_incident}")
    L.append(f"- open alerts: {'none in ops report' if 'ACTION' not in ops_v else 'SEE OPS REPORT'}")

    L.append("\n## 2. LIVE STATUS")
    if not live_fills:
        L.append("**No live fills yet.** (fills.csv on this host is empty; MT5 fills land "
                 "on the VPS ledger. Equity/positions: see `python status.py` on the VPS "
                 "or the daily ledger line.)")
    else:
        L.append(f"- fills today: {len(fills_today)} | this month: {len(live_fills)} | "
                 f"latest: {latest_fill}")
        L.append(f"- slippage avg: {num('slippage_bps')} | spread avg: {num('spread_bps')}")
        L.append("- execution status: measuring (see tools/analyze_execution.py report)")

    L.append("\n## 3. SHADOW STATUS")
    L.append(f"Accumulation: `{bar(sh_days, SHADOW_MIN_DAYS)}` days toward the "
             f"pre-registered {SHADOW_MIN_DAYS}-day verdict minimum.")
    if streams:
        status = ("READY FOR REVIEW" if sh_days >= SHADOW_MIN_DAYS else "WATCHING")
        L.append(f"- ETF survivors ({len(streams)} streams): **{status}** "
                 f"({sh_days} day(s); rule frozen in ETF_FORWARD_SHADOW_REVIEW)")
    else:
        L.append("- ETF survivors: **INSUFFICIENT DATA** (no shadow rows)")
    L.append(f"- VIX term-structure gate: **WAITING** (needs a backwardation episode; "
             f"{sh_days} quiet day(s) logged)")

    L.append("\n## 4. RESEARCH STATUS (from RESEARCH_BACKLOG.md)")
    L.append(f"- READY {totals[5]} | SHADOW {totals[1]} | WAITING {totals[2]} | "
             f"REJECTED {totals[3]} | ARCHIVED {totals[4]}")
    L.append("- discovery: **FROZEN** until month-end")

    L.append("\n## 5. PROP READINESS")
    L.append("- current: **DESIGN READY / EVIDENCE PENDING -- DO NOT BUY CHALLENGES YET**")
    L.append("- top blockers: (1) clean month of statistics (2) execution costs unmeasured "
             "(3) bracket closes invisible -> MT5 history export (full list: PROP_READINESS.md)")
    L.append(f"- countdown to month-end review: **{days_left} days**")

    L.append("\n## 6. TODAY")
    for t in today_block[:3]:
        L.append(f"- {t}")

    L.append("\n## 7. NEXT DECISION")
    L.append(f"**Month 1 committee review** -- expected **~{MONTH_END.strftime('%d %b %Y')}** "
             f"({days_left} days). Input: MONTHLY_EVIDENCE_COMMITTEE + MONTH_1_LIVE_REPORT "
             f"(pre-registered criteria). Outcome: buy 2-3 parallel challenges, or stop free.")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"wrote dashboard/COMMAND_CENTER.md  [health {health}] [today: {today_block[0][:50]}...]")


if __name__ == "__main__":
    main()
