#!/usr/bin/env bash
# install_git_hook.sh — install the post-commit hook that runs obsidian_bridge.py
#
# Usage: bash scripts/install_git_hook.sh
#
# Creates .git/hooks/post-commit (idempotent — safe to re-run).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK_PATH="$REPO_ROOT/.git/hooks/post-commit"

HOOK_CONTENT='#!/usr/bin/env bash
# Auto-generated by scripts/install_git_hook.sh
# Runs the Obsidian bridge after every commit.
set -euo pipefail

# Skip bridge auto-commits to prevent infinite loop
LAST_MSG="$(git log -1 --format=%s)"
if echo "$LAST_MSG" | grep -q "\[bridge-auto\]"; then
    exit 0
fi

cd "$(git rev-parse --show-toplevel)"
python3 scripts/obsidian_bridge.py --post-commit 2>&1 || true
'

# Check for existing hook
if [[ -f "$HOOK_PATH" ]]; then
    if grep -q "obsidian_bridge.py" "$HOOK_PATH" 2>/dev/null; then
        echo "Post-commit hook already installed — updating."
    else
        echo "WARNING: $HOOK_PATH already exists and does not reference obsidian_bridge.py."
        echo "Backing up to $HOOK_PATH.bak"
        cp "$HOOK_PATH" "$HOOK_PATH.bak"
    fi
fi

echo "$HOOK_CONTENT" > "$HOOK_PATH"
chmod +x "$HOOK_PATH"
echo "Installed post-commit hook → $HOOK_PATH"
echo "The Obsidian bridge will run automatically after each commit."
